sudo: required
dist: precise
language: php
php:
- 5.7
- 7.0
- 7.1
- 7.2
- 7.3
- hhvm
matrix:
  allow_failures:
  - php: hhvm
  fast_finish: true
before_script:
- composer self-update
- composer install
script:
- CLIENT_ID=AdV4d6nLHabWLyemrw4BKdO9LjcnioNIOgoz7vD611ObbDUL0kJQfzrdhXEBwnH8QmV-7XZjvjRWn0kg CLIENT_SECRET=EPKoPC_haZMTq5uM9WXuzoxUVdgzVqHyD5avCyVC1NCIUJeVaNNUZMnzduYIqrdw-carG9LBAizFGMyK composer unit
